abstract: Interprocess Publish/Subscribe channels
author: Audrey Tang <cpan@audreyt.org>
distribution_type: module
generated_by: Module::Install version 0.64
license: MIT
name: IPC-PubSub
no_index: 
  directory: 
    - inc
    - t
requires: 
  Class::Accessor::Fast: 0
  DBM::Deep: 0
  Data::UUID: 0
  perl: 5.005
version: 0.11
