--- 
abstract: Interprocess Publish/Subscribe channels
author: Audrey Tang <cpan@audreyt.org>
distribution_type: module
generated_by: Module::Install version 0.64
license: MIT
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: IPC-PubSub
no_index: 
  directory: 
    - inc
    - t
requires: 
  Class::Accessor::Fast: 0
  DBM::Deep: 0
  Data::UUID: 0
  Time::HiRes: 0
  perl: 5.6.0
version: 0.26
